import { type Page, type Locator } from '@playwright/test';

export class ResetPasswordPage {
  readonly page: Page;
  readonly passwordInput: Locator;
  readonly confirmPasswordInput: Locator;
  // TASK-301: the raw, unindexed locator (as opposed to passwordInput /
  // confirmPasswordInput, which each pin to a single nth() index) — needed to
  // assert "there are ZERO password inputs on the invalid-oobCode error
  // card" (use case 3). `.nth(0)` on an empty match set still resolves to a
  // locator whose intent is "the first one", which is the wrong shape for a
  // count-based absence check.
  readonly passwordInputs: Locator;
  readonly submitButton: Locator;
  readonly mismatchError: Locator;
  readonly invalidCodeMessage: Locator;
  readonly backToLoginLink: Locator;
  readonly requestNewLink: Locator;

  constructor(page: Page) {
    this.page = page;
    this.passwordInputs = page.locator('input[type="password"]');
    this.passwordInput = this.passwordInputs.nth(0);
    this.confirmPasswordInput = this.passwordInputs.nth(1);
    this.submitButton = page.getByRole('button', { name: /reset|restablecer/i });
    this.mismatchError = page.locator('.text-rust', { hasText: /match|coinciden/i });
    this.invalidCodeMessage = page.locator('text=✗');
    this.backToLoginLink = page.locator('a[href="/login"]');
    this.requestNewLink = page.locator('a[href="/forgot-password"]');
  }

  async goto(oobCode?: string) {
    const params = oobCode ? `?oobCode=${oobCode}` : '';
    await this.page.goto(`/reset-password${params}`);
  }

  /**
   * TASK-301: navigates using a REAL reset link generated by
   * admin.generatePasswordResetLink(email) (see e2e/helpers/admin.ts). That
   * link points at Firebase's own hosted action handler, not this app, so it
   * is never navigated to directly — only its `oobCode` query param is
   * lifted out and driven through this app's own /reset-password route,
   * exactly as a user arriving from the real email would (mode/apiKey/lang
   * are Firebase-handler-only params ResetPasswordView.vue never reads).
   */
  async gotoWithLink(link: string) {
    const oobCode = new URL(link).searchParams.get('oobCode');
    if (!oobCode) {
      throw new Error(`TASK-301: generatePasswordResetLink returned a link with no oobCode param: ${link}`);
    }
    await this.goto(oobCode);
  }

  async fillPasswords(password: string, confirm: string) {
    await this.passwordInput.fill(password);
    await this.confirmPasswordInput.fill(confirm);
  }
}
