// Shared keyword/filter constants used by AdvancedFilterModal (both Scryfall search and collection filter)
// Complete through TMNT (Dec 2025) + Lorwyn Eclipsed (Jan 2026)

interface KeywordOption {
  value: string
  label: string
}

// ============ 1. COMBAT ABILITIES (ordered by frequency) ============
export const combatAbilities: KeywordOption[] = [
  // Tier 1 — Evergreen staples
  { value: 'flying', label: 'Flying' },
  { value: 'trample', label: 'Trample' },
  { value: 'deathtouch', label: 'Deathtouch' },
  { value: 'haste', label: 'Haste' },
  { value: 'lifelink', label: 'Lifelink' },
  { value: 'first strike', label: 'First Strike' },
  // Tier 2 — Evergreen / deciduous
  { value: 'double strike', label: 'Double Strike' },
  { value: 'hexproof', label: 'Hexproof' },
  { value: 'flash', label: 'Flash' },
  { value: 'vigilance', label: 'Vigilance' },
  { value: 'menace', label: 'Menace' },
  { value: 'reach', label: 'Reach' },
  { value: 'ward', label: 'Ward' },
  // Tier 3 — Common keyword abilities
  { value: 'indestructible', label: 'Indestructible' },
  { value: 'defender', label: 'Defender' },
  { value: 'protection', label: 'Protection' },
  { value: 'prowess', label: 'Prowess' },
  { value: 'shroud', label: 'Shroud' },
  // Tier 4 — Legacy / retired combat keywords
  { value: 'wither', label: 'Wither' },
  { value: 'infect', label: 'Infect' },
  { value: 'shadow', label: 'Shadow' },
  { value: 'fear', label: 'Fear' },
  { value: 'intimidate', label: 'Intimidate' },
  { value: 'skulk', label: 'Skulk' },
  { value: 'flanking', label: 'Flanking' },
  { value: 'afflict', label: 'Afflict' },
  { value: 'bushido', label: 'Bushido' },
  { value: 'horsemanship', label: 'Horsemanship' },
  { value: 'phasing', label: 'Phasing' },
  { value: 'banding', label: 'Banding' },
  { value: 'absorb', label: 'Absorb' },
  { value: 'rampage', label: 'Rampage' },
  { value: 'poisonous', label: 'Poisonous' },
]

// ============ 2. COMMON EFFECTS (subcategories) ============
export const commonEffects = {
  removal: [
    { value: 'destroy', label: 'Destroy' },
    { value: 'exile', label: 'Exile' },
    { value: 'sacrifice', label: 'Sacrifice' },
    { value: 'counter', label: 'Counter' },
    { value: 'return to hand', label: 'Bounce' },
    { value: 'fight', label: 'Fight' },
  ],
  cardAdvantage: [
    { value: 'draw', label: 'Draw' },
    { value: 'scry', label: 'Scry' },
    { value: 'surveil', label: 'Surveil' },
    { value: 'mill', label: 'Mill' },
    { value: 'search your library', label: 'Tutor' },
    { value: 'explore', label: 'Explore' },
    { value: 'discard', label: 'Discard' },
    { value: 'investigate', label: 'Investigate' },
    { value: 'manifest', label: 'Manifest' },
    { value: 'connive', label: 'Connive' },
  ],
  tokens: [
    { value: 'treasure token', label: 'Treasure' },
    { value: 'food token', label: 'Food' },
    { value: 'clue token', label: 'Clue' },
    { value: 'blood token', label: 'Blood' },
    { value: 'map token', label: 'Map' },
    { value: 'powerstone token', label: 'Powerstone' },
    { value: 'create a token', label: 'Create Token' },
    { value: 'populate', label: 'Populate' },
    { value: 'incubate', label: 'Incubate' },
  ],
  counters: [
    { value: 'proliferate', label: 'Proliferate' },
    { value: '+1/+1 counter', label: '+1/+1' },
    { value: '-1/-1 counter', label: '-1/-1' },
    { value: 'amass', label: 'Amass' },
    { value: 'bolster', label: 'Bolster' },
    { value: 'support', label: 'Support' },
  ],
  control: [
    { value: 'gain control', label: 'Steal' },
    { value: 'goad', label: 'Goad' },
    { value: 'detain', label: 'Detain' },
    { value: 'tap', label: 'Tap' },
    { value: 'untap', label: 'Untap' },
  ],
}

export const allCommonEffects: KeywordOption[] = [
  ...commonEffects.removal,
  ...commonEffects.cardAdvantage,
  ...commonEffects.tokens,
  ...commonEffects.counters,
  ...commonEffects.control,
]

// ============ 3. TRIGGERS ============
export const triggerKeywords: KeywordOption[] = [
  { value: 'enters the battlefield', label: 'ETB' },
  { value: 'dies', label: 'Dies' },
  { value: 'whenever ~ attacks', label: 'Attack' },
  { value: 'deals combat damage', label: 'Combat Damage' },
  { value: 'when you cast', label: 'Cast' },
  { value: 'whenever you sacrifice', label: 'Sacrifice' },
  { value: 'whenever you gain life', label: 'Lifegain' },
  { value: 'whenever a creature dies', label: 'Creature Dies' },
  { value: 'beginning of your upkeep', label: 'Upkeep' },
  { value: 'beginning of your end step', label: 'End Step' },
  { value: 'leaves the battlefield', label: 'LTB' },
]

// ============ 4. SET MECHANICS ============
export const setMechanics = {
  meta: [
    { value: 'cascade', label: 'Cascade' },
    { value: 'delve', label: 'Delve' },
    { value: 'affinity', label: 'Affinity' },
    { value: 'energy', label: 'Energy' },
    { value: 'convoke', label: 'Convoke' },
    { value: 'storm', label: 'Storm' },
    { value: 'dredge', label: 'Dredge' },
    { value: 'annihilator', label: 'Annihilator' },
    { value: 'buyback', label: 'Buyback' },
    { value: 'overload', label: 'Overload' },
    { value: 'split second', label: 'Split Second' },
  ],
  popular: [
    { value: 'flashback', label: 'Flashback' },
    { value: 'cycling', label: 'Cycling' },
    { value: 'kicker', label: 'Kicker' },
    { value: 'multikicker', label: 'Multikicker' },
    { value: 'evoke', label: 'Evoke' },
    { value: 'unearth', label: 'Unearth' },
    { value: 'madness', label: 'Madness' },
    { value: 'suspend', label: 'Suspend' },
    { value: 'escape', label: 'Escape' },
    { value: 'ninjutsu', label: 'Ninjutsu' },
    { value: 'morph', label: 'Morph' },
    { value: 'dash', label: 'Dash' },
    { value: 'bestow', label: 'Bestow' },
    { value: 'disturb', label: 'Disturb' },
    { value: 'encore', label: 'Encore' },
    { value: 'fuse', label: 'Fuse' },
    { value: 'jump-start', label: 'Jump-Start' },
    { value: 'miracle', label: 'Miracle' },
    { value: 'rebound', label: 'Rebound' },
    { value: 'retrace', label: 'Retrace' },
  ],
  recent: [
    // Lost Caverns / Wilds of Eldraine (2023)
    { value: 'discover', label: 'Discover' },
    { value: 'craft', label: 'Craft' },
    { value: 'descend', label: 'Descend' },
    { value: 'celebration', label: 'Celebration' },
    { value: 'bargain', label: 'Bargain' },
    // Murders at Karlov Manor / Outlaws (2024)
    { value: 'collect evidence', label: 'Collect Evidence' },
    { value: 'suspect', label: 'Suspect' },
    { value: 'disguise', label: 'Disguise' },
    { value: 'cloak', label: 'Cloak' },
    { value: 'plot', label: 'Plot' },
    { value: 'freerunning', label: 'Freerunning' },
    // Bloomburrow / Duskmourn (2024)
    { value: 'offspring', label: 'Offspring' },
    { value: 'expend', label: 'Expend' },
    { value: 'forage', label: 'Forage' },
    { value: 'valiant', label: 'Valiant' },
    { value: 'impending', label: 'Impending' },
    { value: 'eerie', label: 'Eerie' },
    { value: 'manifest dread', label: 'Manifest Dread' },
    { value: 'delirium', label: 'Delirium' },
    { value: 'survival', label: 'Survival' },
    // Foundations (2024)
    { value: 'gift', label: 'Gift' },
    // Aetherdrift (Feb 2025)
    { value: 'exhaust', label: 'Exhaust' },
    { value: 'start your engines', label: 'Start Your Engines' },
    { value: 'max speed', label: 'Max Speed' },
    // Tarkir: Dragonstorm (Apr 2025)
    { value: 'flurry', label: 'Flurry' },
    { value: 'endure', label: 'Endure' },
    { value: 'mobilize', label: 'Mobilize' },
    { value: 'harmonize', label: 'Harmonize' },
    { value: 'renew', label: 'Renew' },
    { value: 'behold', label: 'Behold' },
    // Final Fantasy (Jun 2025)
    { value: 'job select', label: 'Job Select' },
    { value: 'tiered', label: 'Tiered' },
    // Edge of Eternities (Aug 2025)
    { value: 'warp', label: 'Warp' },
    // Spider-Man (Sep 2025)
    { value: 'web-slinging', label: 'Web-Slinging' },
    { value: 'mayhem', label: 'Mayhem' },
    { value: 'double team', label: 'Double Team' },
    // TMNT (Dec 2025)
    { value: 'sneak', label: 'Sneak' },
    { value: 'solved', label: 'Solved' },
    // Lorwyn Eclipsed (Jan 2026)
    { value: 'blight', label: 'Blight' },
    { value: 'vivid', label: 'Vivid' },
  ],
  other: [
    { value: 'adapt', label: 'Adapt' },
    { value: 'afterlife', label: 'Afterlife' },
    { value: 'alliance', label: 'Alliance' },
    { value: 'ascend', label: 'Ascend' },
    { value: 'backup', label: 'Backup' },
    { value: 'battle cry', label: 'Battle Cry' },
    { value: 'blitz', label: 'Blitz' },
    { value: 'boast', label: 'Boast' },
    { value: 'casualty', label: 'Casualty' },
    { value: 'changeling', label: 'Changeling' },
    { value: 'channel', label: 'Channel' },
    { value: 'cleave', label: 'Cleave' },
    { value: 'companion', label: 'Companion' },
    { value: 'compleated', label: 'Compleated' },
    { value: 'corrupted', label: 'Corrupted' },
    { value: 'daybound', label: 'Daybound' },
    { value: 'decayed', label: 'Decayed' },
    { value: 'demonstrate', label: 'Demonstrate' },
    { value: 'devoid', label: 'Devoid' },
    { value: 'domain', label: 'Domain' },
    { value: 'embalm', label: 'Embalm' },
    { value: 'emerge', label: 'Emerge' },
    { value: 'enlist', label: 'Enlist' },
    { value: 'escalate', label: 'Escalate' },
    { value: 'eternalize', label: 'Eternalize' },
    { value: 'evolve', label: 'Evolve' },
    { value: 'exalted', label: 'Exalted' },
    { value: 'exploit', label: 'Exploit' },
    { value: 'extort', label: 'Extort' },
    { value: 'fabricate', label: 'Fabricate' },
    { value: 'foretell', label: 'Foretell' },
    { value: 'heroic', label: 'Heroic' },
    { value: 'improvise', label: 'Improvise' },
    { value: 'landfall', label: 'Landfall' },
    { value: 'living metal', label: 'Living Metal' },
    { value: 'living weapon', label: 'Living Weapon' },
    { value: 'magecraft', label: 'Magecraft' },
    { value: 'megamorph', label: 'Megamorph' },
    { value: 'melee', label: 'Melee' },
    { value: 'mentor', label: 'Mentor' },
    { value: 'modified', label: 'Modified' },
    { value: 'monstrosity', label: 'Monstrosity' },
    { value: 'mutate', label: 'Mutate' },
    { value: 'myriad', label: 'Myriad' },
    { value: 'outlast', label: 'Outlast' },
    { value: 'persist', label: 'Persist' },
    { value: 'prototype', label: 'Prototype' },
    { value: 'raid', label: 'Raid' },
    { value: 'ravenous', label: 'Ravenous' },
    { value: 'read ahead', label: 'Read Ahead' },
    { value: 'reconfigure', label: 'Reconfigure' },
    { value: 'renown', label: 'Renown' },
    { value: 'revolt', label: 'Revolt' },
    { value: 'riot', label: 'Riot' },
    { value: 'saddle', label: 'Saddle' },
    { value: 'scavenge', label: 'Scavenge' },
    { value: 'spectacle', label: 'Spectacle' },
    { value: 'spree', label: 'Spree' },
    { value: 'squad', label: 'Squad' },
    { value: 'surge', label: 'Surge' },
    { value: 'threshold', label: 'Threshold' },
    { value: 'toxic', label: 'Toxic' },
    { value: 'training', label: 'Training' },
    { value: 'undaunted', label: 'Undaunted' },
    { value: 'undying', label: 'Undying' },
    { value: 'unleash', label: 'Unleash' },
  ],
  classic: [
    { value: 'aftermath', label: 'Aftermath' },
    { value: 'amplify', label: 'Amplify' },
    { value: 'assist', label: 'Assist' },
    { value: 'bloodthirst', label: 'Bloodthirst' },
    { value: 'champion', label: 'Champion' },
    { value: 'cipher', label: 'Cipher' },
    { value: 'conspire', label: 'Conspire' },
    { value: 'constellation', label: 'Constellation' },
    { value: 'crew', label: 'Crew' },
    { value: 'cumulative upkeep', label: 'Cumulative Upkeep' },
    { value: 'dethrone', label: 'Dethrone' },
    { value: 'devour', label: 'Devour' },
    { value: 'echo', label: 'Echo' },
    { value: 'entwine', label: 'Entwine' },
    { value: 'epic', label: 'Epic' },
    { value: 'fading', label: 'Fading' },
    { value: 'forecast', label: 'Forecast' },
    { value: 'graft', label: 'Graft' },
    { value: 'gravestorm', label: 'Gravestorm' },
    { value: 'haunt', label: 'Haunt' },
    { value: 'hellbent', label: 'Hellbent' },
    { value: 'hideaway', label: 'Hideaway' },
    { value: 'ingest', label: 'Ingest' },
    { value: 'level up', label: 'Level Up' },
    { value: 'metalcraft', label: 'Metalcraft' },
    { value: 'modular', label: 'Modular' },
    { value: 'morbid', label: 'Morbid' },
    { value: 'offering', label: 'Offering' },
    { value: 'partner', label: 'Partner' },
    { value: 'provoke', label: 'Provoke' },
    { value: 'prowl', label: 'Prowl' },
    { value: 'reinforce', label: 'Reinforce' },
    { value: 'replicate', label: 'Replicate' },
    { value: 'ripple', label: 'Ripple' },
    { value: 'soulbond', label: 'Soulbond' },
    { value: 'soulshift', label: 'Soulshift' },
    { value: 'splice', label: 'Splice' },
    { value: 'sunburst', label: 'Sunburst' },
    { value: 'transfigure', label: 'Transfigure' },
    { value: 'transmute', label: 'Transmute' },
    { value: 'tribute', label: 'Tribute' },
    { value: 'vanishing', label: 'Vanishing' },
  ],
}

export const allSetMechanics: KeywordOption[] = [
  ...setMechanics.meta,
  ...setMechanics.popular,
  ...setMechanics.recent,
  ...setMechanics.other,
  ...setMechanics.classic,
]

// ============ SPECIAL TYPES ============
export const specialTypes: KeywordOption[] = [
  { value: 'legendary', label: 'Legendary' },
  { value: 'equipment', label: 'Equipment' },
  { value: 'aura', label: 'Aura' },
  { value: 'vehicle', label: 'Vehicle' },
  { value: 'saga', label: 'Saga' },
  { value: 'modal double-faced', label: 'MDFC' },
  { value: 'transform', label: 'DFC' },
  { value: 'snow', label: 'Snow' },
  { value: 'room', label: 'Room' },
  { value: 'omen', label: 'Omen' },
  { value: 'adventure', label: 'Adventure' },
  { value: 'battle', label: 'Battle' },
]

// ============ CREATURE TYPES (common MTG subtypes for Scryfall mode) ============
export const creatureTypes: KeywordOption[] = [
  // Major races
  { value: 'human', label: 'Human' },
  { value: 'elf', label: 'Elf' },
  { value: 'goblin', label: 'Goblin' },
  { value: 'merfolk', label: 'Merfolk' },
  { value: 'dwarf', label: 'Dwarf' },
  { value: 'faerie', label: 'Faerie' },
  { value: 'orc', label: 'Orc' },
  { value: 'spirit', label: 'Spirit' },
  { value: 'elemental', label: 'Elemental' },
  { value: 'soldier', label: 'Soldier' },
  { value: 'wizard', label: 'Wizard' },
  { value: 'warrior', label: 'Warrior' },
  { value: 'cleric', label: 'Cleric' },
  { value: 'rogue', label: 'Rogue' },
  { value: 'knight', label: 'Knight' },
  { value: 'shaman', label: 'Shaman' },
  { value: 'druid', label: 'Druid' },
  { value: 'monk', label: 'Monk' },
  // Iconic creatures
  { value: 'dragon', label: 'Dragon' },
  { value: 'angel', label: 'Angel' },
  { value: 'demon', label: 'Demon' },
  { value: 'hydra', label: 'Hydra' },
  { value: 'sphinx', label: 'Sphinx' },
  { value: 'dinosaur', label: 'Dinosaur' },
  { value: 'phoenix', label: 'Phoenix' },
  { value: 'beast', label: 'Beast' },
  // Tribal / undead
  { value: 'zombie', label: 'Zombie' },
  { value: 'vampire', label: 'Vampire' },
  { value: 'werewolf', label: 'Werewolf' },
  { value: 'skeleton', label: 'Skeleton' },
  // Animals & nature
  { value: 'cat', label: 'Cat' },
  { value: 'dog', label: 'Dog' },
  { value: 'bird', label: 'Bird' },
  { value: 'snake', label: 'Snake' },
  { value: 'rat', label: 'Rat' },
  { value: 'spider', label: 'Spider' },
  { value: 'insect', label: 'Insect' },
  { value: 'treefolk', label: 'Treefolk' },
  { value: 'fungus', label: 'Fungus' },
  // Artifact creatures
  { value: 'golem', label: 'Golem' },
  { value: 'construct', label: 'Construct' },
  { value: 'robot', label: 'Robot' },
  // Other popular
  { value: 'pirate', label: 'Pirate' },
  { value: 'scout', label: 'Scout' },
  { value: 'assassin', label: 'Assassin' },
  { value: 'berserker', label: 'Berserker' },
  { value: 'sliver', label: 'Sliver' },
  { value: 'horror', label: 'Horror' },
  { value: 'god', label: 'God' },
  { value: 'turtle', label: 'Turtle' },
  { value: 'mutant', label: 'Mutant' },
  { value: 'ninja', label: 'Ninja' },
]

export const allCreatureTypes: KeywordOption[] = [...creatureTypes]

// ============ FORMAT OPTIONS ============
export const formatOptions: KeywordOption[] = [
  { value: 'standard', label: 'Standard' },
  { value: 'modern', label: 'Modern' },
  { value: 'legacy', label: 'Legacy' },
  { value: 'vintage', label: 'Vintage' },
  { value: 'commander', label: 'Commander' },
  { value: 'pioneer', label: 'Pioneer' },
  { value: 'pauper', label: 'Pauper' },
]

// All keywords flat list (for search)
const allKeywords: KeywordOption[] = [
  ...combatAbilities,
  ...allCommonEffects,
  ...triggerKeywords,
  ...allSetMechanics,
  ...specialTypes,
  ...allCreatureTypes,
]

export const getKeywordLabel = (value: string): string => {
  return allKeywords.find(kw => kw.value === value)?.label || value
}
